name: Deploy MkDocs
on:
  push:
    branches: [ main ]
permissions:
  contents: write
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install -r requirements.txt
      - name: Install TeX Live (latexmk)
        run: sudo apt-get update && sudo apt-get install -y texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended latexmk
      - name: Compile CS103 Lecture 1 PDF
        run: |
          cd courses/CS103A/01-intro-set-theory
          latexmk -pdf -interaction=nonstopmode -halt-on-error lecture1.tex
          mkdir -p ../../../docs/courses/CS103A
          cp lecture1.pdf ../../../docs/courses/CS103A/
      - run: mkdocs build --strict
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
